---
- name: Openshift integration 
  hosts: all
  tasks:
   - name: Create a Openshift namespace--Guestbook
     redhat.openshift.k8s:
       name: guestbook
       api_version: v1
       kind: Namespace
       state: present
     delegate_to: localhost
