---
- name: Get POD Status
  hosts: all
  tasks:
   - name: Get Pod status
     shell: |
       oc login -u opentlc-mgr -p r3dh4t1! console-openshift-console.apps.cluster-7c6zd.7c6zd.sandbox2306.opentlc.com
       oc get pods -n finacle
