---
- name: Openshift integration 
  hosts: all
  tasks:
   - name: Configure Secret
     redhat.openshift.k8s:
       state: present   
       definition:
         apiVersion: v1
         kind: Secret
         metadata:
         metadata:
           name: mysecret
         type: Opaque 
         data:
           username: dXNlci1uYW1l
           password: cGFzc3dvcmQ=
