---
- name: Openshift integration 
  hosts: all
  tasks:
   - name: Configure Secret
     redhat.openshift.k8s:
       state: present   
       definition:
         apiVersion: v1
         kind: Secret
         metadata:
           name: test
           namespace: bookinfo
         type: Opaque 
         stringData:
           username: dXNlci1uYW1l
           password: "{{ pass }}"
     delegate_to: localhost
