---
- name: Openshift integration 
  hosts: all
  tasks:
   - name: Create a Service for Redis Leader application
     redhat.openshift.k8s:
       state: present   
       definition:
         apiVersion: v1
         kind: Service
         metadata:
           name: redis-leader
           namespace: guestbook
           labels:
             app: redis
             tier: backend
             role: leader
         spec:
           ports:
           - port: 6379
             targetPort: 6379
           selector:
             app: redis
             tier: backend
             role: leader
     delegate_to: localhost
