---
- name: Openshift integration 
  hosts: all
  tasks:
   - name: Create a Service for Book Info application
     redhat.openshift.k8s:
       state: present   
       definition:
         apiVersion: v1
         kind: Service
         metadata:
           name: book-import
           namespace: bookinfo
           labels:
             name: book-import
         spec:
           type: ClusterIP
           ports:
           - port: 80
             targetPort: 8080
           selector:
             name: book-import
     delegate_to: localhost
