---
- name: Openshift integration 
  hosts: all
  tasks:
   - name: Create a Service for Book Info application
     redhat.openshift.k8s:
       state: present   
       definition:
         apiVersion: v1
         kind: Service
         metadata:
           name: book-import
           labels:
             name: book-import
         spec:
           type: ClusterIP
           ports:
             - port: 80
               targetPort: 8080
               protocol: TCP
           selector:
             name: book-import
